const ADD_ENTRADA = "ADD_ENTRADA";
const GET_ALL_ENTRADA = "GET_ALL_ENTRADA";
const UPDATE_ENTRADA = "UPDATE_ENTRADA";
const DESTROY_ENTRADA = "DESTROY_ENTRADA";

module.exports = {
    ADD_ENTRADA,
    GET_ALL_ENTRADA,
    UPDATE_ENTRADA,
    DESTROY_ENTRADA
}