const ADD_SAIDA = "ADD_SAIDA";
const GET_ALL_SAIDA = "GET_ALL_SAIDA";
const UPDATE_SAIDA = "UPDATE_SAIDA";
const DESTROY_SAIDA = "DESTROY_SAIDA";

module.exports = {
    ADD_SAIDA,
    GET_ALL_SAIDA,
    UPDATE_SAIDA,
    DESTROY_SAIDA
}